---
title: "Systematic Review Hypotheses"
author: "Willson Gaul"
date: "10 August 2018"
output:
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, message = F, warning = F, cache = F)
```

*Note* - Wikipedia says Chi-square test assumes categories are mutually exclusive.  Jon thinks it's actually that they need to be independent (counts in cells need to be independent), so mutually exclusive categories isn't actually required as long as the categories aren't correlated. 

**About 12 tests planned.**

**Expect 300 studies (n = 300)**

Number of tests could be reduced if I can find something like a chi-squared test that just does an overall test for independence between two variables. 

## Authors and Data Providing Institutions

**Who choses to use biological records data?**

$H_a$: The first author is more likely to use data held by their own institution than by other institutions.

$H_0$: The number of studies with a lead author from the institution that provided the data is the same as expected by chance.

*Proposed Test*: Permutation test of lead author institutions.  


## Temporal Extent

$H_a$: The mean temporal extent of studies using only what, where, when data is longer than the mean temporal extent of studies using richer data types. 

$H_0$: Data type does not affect the mean temporal extent of studies.  //  The mean temporal extent of studies using what, where, when-only data is the same as the mean temporal extent of studies using other data types. 

*Proposed Test*: Linear regression with natural-log transformed time (in years) as the outcome and data types as predictors.

## Study Question Paradigm

**What is the most popular study question paradigm?**

$H_a$: Some broad study question paradigms are more common than others in studies using biological records.

$H_0$: The number of studies pursuing each of the broad study question paradigms is the same.

*Proposed Test* One Poisson regression with study question paradigm as predictor. 



## Data Type and Analysis Approach

The question here is whether the data type affects the analysis approach.

Reduce this to fewer data types that I think are most important *a-priori*.

Those are (in order of importance by my guess):

1) sampling effort reported
2) abundance
3) detection / non-detection

$H1_a$: Different types of data are analysed with different broad analysis approaches.

$H1_0$: Different types of data are analysed with the same broad analysis approaches.

$H2_a$: Non-detection, survey effort, and abundance data each increases the probability studies will use a model-based analysis (either inferential or predictive) rather than a descriptive analysis.

$H2_0$: Non-detection, survey effort, and abundance data do not affect the probability studies will use a model-based analysis (either inferential or predictive) rather than a descriptive analysis.

*Proposed Test*: Logistic Regression with probability of statistical / model-based results as the outcome and data types as predictors. For first hypothesis, fit the full model and the model with only the intercept (what where when data only) and test for significance of all data types.  Then, do this individually removing each data type to get estimate of significance for each data type. (4 regressions total)

Full model: 

$logit(P_{model}) = \beta_0 + \beta_1 * non detection + \beta_2 * survey effort + \beta_3 * abundance$

## Specific Study Focus

$H1_a$: Studies with different specific focuses use different data types.

$H1_0$: The data type used is independent of the specific main focus of the study. 

$H2_a$: Data type affects the rate at which the data are used to to answer questions with each of the main focuses.  

$H2_0$: The rates at which studies with each main focus occur is not affected by data type.

*Proposed Test*: Two stages of analysis.  

1) Chi-squared test of independence between data type and study focus.  Data types are: what, where, when; survey effort; abundance; detection / non-detection.  Study focuses are: species distribution; species abundance/population size; phenology; temporal trends.  

2) If test 1 shows significant differences, I will not test all possible differences, but rather will do separate Poisson regressions to test the affect on counts of specific types of studies of adding supplementary data types of interest. Which study questions to test is based on what I think is of interest.
    1) `count of temporal trends studies ~ survey effort + abundance + detection / non-detection`
    2) `count of abundance studies ~ survey effort + abundance + detection / non-detection`
    3) `count of distribution studies ~ survey effort + abundance + detection / non-detection`
    4) `count of phenology studies ~ survey effort + abundance + detection / non-detection`
    





----------------------------------------------------------------

### No Statistical Testing?  Descriptive Results Only

## Spatial Extent

Question is of interest but I think I might not have the data to answer it b/c I am limiting to UK & Ireland, so distribution of areas will have lots that are UK-sized.

$H_a$: The mean spatial extent of studies using only what, where, when data is larger than the mean spatial extent of studies using richer data types. 

$H_0$: Data type does not affect the mean spatial extent of studies.

*Proposed Test*: Linear regression with area (km$^2$) as the outcome and data types as predictors.

## Data Type and Study Question Paradigm

**What data types are used for each study question paradigm?**

Drop compiled individual from coding.  For this analysis, use only community and individual species question types.  Keep coding "Methodology" but don't include it here, because I think in most cases the methodolgy development will be developing methods for analysing either individual species or community questions.  So the community/individual sp paradigm dichotomy still works. 

$H_a$: Different broad study question paradigms use different data types.

$H_0$: Data type does not affect study question paradigm.

*Proposed Test* Two separate Poisson regressions with data types as predictors and counts of number of studies using each study question paradigm as responses.

Alternatively: 

After meeting with Jon (10 Aug), could do something like:

`count ~ dt_abundance + dt_samplingEffort + sq_community + sq_individualSp + dt_abundance:sq_community + dt_abundance:sq_individualSp + ...`

OR, could do something like this:


| Module | Var2 | Count |
|--------|------|-------|
| Maths | Irish + Male | 8 |
| Maths | Irish + Femal | |
| Maths | Not Irish + Male | |
| Maths | Not Irish + Female | |
| History | Irish + Male | | 
| ... | ... | ... |

Where Var2 has every combination of the variables along the top row of a pseudo-contingency table (in my case, all the data type variables).  Could then use Poisson regression to fit:

`count ~ Module + Var2 + Module:Var2` 

and

`count ~ Module + Var2`

to test for than interaction (whether there is a dependency between Module and Var2, or in my case between data type and study question paradigm).  This would test the null hypothesis I've written above, but isn't actually very interesting, b/c it we would immediately then want to know *which* data types affect *which* study question paradigms.


## Specific Study Focus

What are bio recs used for?  Descriptive stats for studies focusing on policy or alien species, testing ecological theory, and testing methods of data correction.

## Spatial Bias Correction

$H_a$: Spatial bias is corrected for more often in studies using inference than in studies using other analysis strategies.

$H_0$: Analysis strategy does not affect the probability that a study corrects for spatial bias.

*Proposed Test*: Logistic regression with analysis strategies as predictors and whether the study corrected for spatial bias as the outcome. 

*Notes*: I will present descriptive statistics of % of studies that correct for spatial bias.  This feels like a weird, weak hypothesis.  Maybe this doesn't need a test?

## Taxonomic Group

$H_a$: Different taxa are studied using different data types. // The probability of using each data type depends on the taxonomic group(s) being studied.

$H_0$: Different taxa are studied using the same data types.  //  The probability of using a given data type does not depend on the taxonomic group(s) being studied (7 logistic regressions)

*Proposed Test*: Seven logistic regressions with taxon groups as binary predictors and probability of a data type as the responses.

*Notes*: From a process perspective this is probably usually a situation of "I want to study earwigs, what data can I get?", so a study is a trial and taxon groups are predictors in 7 logistic regressions estimating the probability of using each data type. 

Alternatively, I suppose I could model it as studies of each taxon being produced at some rate, and that rate depends on the data type (e.g. abundance data being true dramatically reduces the rate at which earwig studies appear). I find this weird from a real-world process standpoint, but maybe it's ok?  **Jon?**

## Role of biological records

No testing planned.  I will present descriptive statistics of proportion of studies using biological records as a response, a predictor, or facilitatively.  

## Prediction performance measure

$H_a$: AUC is used more often than other prediction performance measures.

$H_0$: The number of studies using each prediction performance measure is the same.

*Proposed Test*: `prop.test` to test if proportions are different.

*Notes*: This feels fringe.  I want to code it for my own reference, but perhaps I shouldn't plan to include it in paper.  This is a different discussion that I don't need to get into.

## Specific Analysis methods

Present descriptive statistics of relative frequencies of methods (e.g. GLMs, MaxEnt).  

$H_a$: Different analysis methods are used different amounts. 

$H_0$: Analysis methods are all used the same amount.  This is a straw man if ever there was one.  

*Proposed Test*: Poisson regression?  Does it make sense to do a single Poisson regression with analysis methods as predictors?  This assumes there's some baseline rate at which studies appear and that rate is either increased or decreased by the use of each analysis method.  This isn't actually the process, but is it a valid way to test the hypothesis?

## Authors associated with data provider

**Is any author associated with the data provider?**

**drop?**

$H_a$: Studies are more likely to have at least one author from the institution that provided the biological records than from the institution(s) that provided other prepared data (e.g. climate data, land use/cover, functional traits, night lighting, NDVI, conservation status listing). 

$H_0$: The probability that at least one author on a study is associated with the biological records provider is the same as the probabilities that at least one author on a study is associated with the provider of other types of prepared data.

*Proposed Test*: `prop.test` in R, which seems to report Pearson's chi-squared test statistic.  But I think it can estimate the proportion +- 95% CI for each group, and can then compare those proportions, so doesn't require mutually exclusive groups, like a chi-squared test.  But I remain unsure about this.  Perhaps look at Agresti (2007) *An introduction to categorical data analysis*. 

------------------------------------------------------------------------------

## Variables I might not use

Drop these from coding?  Code just in case?  How to report that, then?

* data gridded
* grid resolution
* non-detection inferred from other presences (DROPED)
* entire taxonomic group analyzed (DROPED)
* results format - hypothesis testing (DROPED)
* compiled individual (DROPED)

## Variables to add

* last author institutions


